// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginuserTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void loginexitoso() {
        driver.get("https://test-qa.inlaze.com/auth/sign-in");
        driver.findElement(By.xpath("//input[@id=\'email\']")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("Correovalido@gmail.com");
        driver.findElement(By.xpath("//input[@id=\'password\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("12345678aA+");
        driver.findElement(By.cssSelector(".fa-solid")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.xpath("//img")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//a[contains(text(),\'Logout\')]")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//label")).click();
        driver.close();
    }
    @Test
    public void loginincompletoemail() {
        driver.get("https://test-qa.inlaze.com/auth/sign-in");
        driver.findElement(By.xpath("//input[@id=\'email\']")).click();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.cssSelector(".w-full > #password")).sendKeys("Teseeewesdfcfgcfg");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".w-full > #password")).click();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.cssSelector(".flex-col:nth-child(2)")).click();
        try {
            Thread.sleep(4000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
    @Test
    public void loginincompletopassword() {
        driver.get("https://test-qa.inlaze.com/auth/sign-in");
        driver.findElement(By.xpath("//input[@id=\'email\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("correoinvalido@yopmail.com");
        driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".w-full > #password")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.cssSelector(".flex-col:nth-child(2)")).click();
        try {
            Thread.sleep(4000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
    @Test
    public void loginnombreuser() {
        driver.get("https://test-qa.inlaze.com/auth/sign-in");
        driver.findElement(By.xpath("//input[@id=\'email\']")).click();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("Correovalido1@gmail.com");
        driver.findElement(By.xpath("//input[@id=\'password\']")).click();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("12345678aB+");
        driver.findElement(By.cssSelector(".fa-solid")).click();
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        assertThat(driver.findElement(By.cssSelector(".flex > .font-bold")).getText(), is("Correo valido 1"));
        driver.close();
    }
    @Test
    public void logininvalido() {
        driver.get("https://test-qa.inlaze.com/auth/sign-in");
        driver.findElement(By.xpath("//input[@id=\'email\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("correoinvalido@yopmail.com");
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("Test123456789");
        driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.cssSelector(".w-full > #password")).click();
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        assertThat(driver.findElement(By.cssSelector(".ml-3")).getText(), is("User not found"));
    }
}
