// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrodeusuarioTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void registrocontraseanocoincide() throws InterruptedException {
        driver.get("https://test-qa.inlaze.com/auth/sign-up");
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        vars.put("randomname", js.executeScript("return (function generateRandomName() {                     var firstNames = [\"John\", \"Jane\", \"Michael\", \"Emily\", \"Chris\", \"Katie\", \"James\", \"Sarah\", \"David\", \"Laura\"];                     var lastNames = [\"Smith\", \"Johnson\", \"Williams\", \"Jones\", \"Brown\", \"Davis\", \"Miller\", \"Wilson\", \"Moore\", \"Taylor\"];                     var firstName = firstNames[Math.floor(Math.random() * firstNames.length)];                     var lastName = lastNames[Math.floor(Math.random() * lastNames.length)];                     return firstName + \" \" + lastName;                 })();"));
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).sendKeys(vars.get("randomname").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.id("email")).click();
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("inlazeuser2@yopmail.com");
        driver.findElement(By.xpath("//input[@id=\'password\']")).click();
        vars.put("generatedpassword1", js.executeScript("return (function generatePassword1() {                     var length = 8,                         charset = \"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+<>?\",                         retVal = \"\";                     retVal += \"abcdefghijklmnopqrstuvwxyz\".charAt(Math.floor(Math.random() * 26));                     retVal += \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\".charAt(Math.floor(Math.random() * 26));                     retVal += \"0123456789\".charAt(Math.floor(Math.random() * 10));                     retVal += \"!@#$%^&*()_+<>?\".charAt(Math.floor(Math.random() * 17));                     for (var i = retVal.length; i < length; ++i) {                         retVal += charset.charAt(Math.floor(Math.random() * charset.length));                     }                     return retVal.split(\'\').sort(function(){return 0.5-Math.random()}).join(\'\');                 })();"));
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys(vars.get("generatedpassword1").toString());
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).click();
        vars.put("generatedpassword2", js.executeScript("return (function generatePassword2() {                     var length = 8,                         charset = \"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+<>?\",                         retVal = \"\";                     retVal += \"abcdefghijklmnopqrstuvwxyz\".charAt(Math.floor(Math.random() * 26));                     retVal += \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\".charAt(Math.floor(Math.random() * 26));                     retVal += \"0123456789\".charAt(Math.floor(Math.random() * 10));                     retVal += \"!@#$%^&*()_+<>?\".charAt(Math.floor(Math.random() * 17));                     for (var i = retVal.length; i < length; ++i) {                         retVal += charset.charAt(Math.floor(Math.random() * charset.length));                     }                     return retVal.split(\'\').sort(function(){return 0.5-Math.random()}).join(\'\');                 })();return (function generatePassword() {                     var length = 8,                         charset = \"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+<>?\",                         retVal = \"\";                     retVal += \"abcdefghijklmnopqrstuvwxyz\".charAt(Math.floor(Math.random() * 26));                     retVal += \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\".charAt(Math.floor(Math.random() * 26));                     retVal += \"0123456789\".charAt(Math.floor(Math.random() * 10));                     retVal += \"!@#$%^&*()_+<>?\".charAt(Math.floor(Math.random() * 17));                     for (var i = retVal.length; i < length; ++i) {                         retVal += charset.charAt(Math.floor(Math.random() * charset.length));                     }                     return retVal.split(\'\').sort(function(){return 0.5-Math.random()}).join(\'\');                 })();"));
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).sendKeys(vars.get("generatedpassword2").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        assertThat(driver.findElement(By.cssSelector(".label-text-alt")).getText(), is("Passwords do not match"));
    }
    @Test
    public void registroexitoso() {
        driver.get("https://test-qa.inlaze.com/auth/sign-up");
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        vars.put("randomname", js.executeScript("return (function generateRandomName() {                     var firstNames = [\"John\", \"Jane\", \"Michael\", \"Emily\", \"Chris\", \"Katie\", \"James\", \"Sarah\", \"David\", \"Laura\"];                     var lastNames = [\"Smith\", \"Johnson\", \"Williams\", \"Jones\", \"Brown\", \"Davis\", \"Miller\", \"Wilson\", \"Moore\", \"Taylor\"];                     var firstName = firstNames[Math.floor(Math.random() * firstNames.length)];                     var lastName = lastNames[Math.floor(Math.random() * lastNames.length)];                     return firstName + \" \" + lastName;                 })();"));
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).sendKeys(vars.get("randomname").toString());
        driver.findElement(By.id("email")).click();
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("inlazeuser2@yopmail.com");
        driver.findElement(By.xpath("//input[@id=\'password\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        vars.put("generatedpassword", js.executeScript("return (function generatePassword() {                     var length = 8,                         charset = \"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+<>?\",                         retVal = \"\";                     retVal += \"abcdefghijklmnopqrstuvwxyz\".charAt(Math.floor(Math.random() * 26));                     retVal += \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\".charAt(Math.floor(Math.random() * 26));                     retVal += \"0123456789\".charAt(Math.floor(Math.random() * 10));                     retVal += \"!@#$%^&*()_+<>?\".charAt(Math.floor(Math.random() * 17));                     for (var i = retVal.length; i < length; ++i) {                         retVal += charset.charAt(Math.floor(Math.random() * charset.length));                     }                     return retVal.split(\'\').sort(function(){return 0.5-Math.random()}).join(\'\');                 })();"));
        vars.put("password", vars.get("generatedpassword").toString());
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys(vars.get("password").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).click();
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).sendKeys(vars.get("password").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        assertThat(driver.findElement(By.cssSelector(".ml-3")).getText(), is("Successful registration!"));
    }
    @Test
    public void registroinvalidocontrasea() {
        driver.get("https://test-qa.inlaze.com/auth/sign-up");
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).click();
        vars.put("randomname", js.executeScript("return (function generateRandomName() {                     var firstNames = [\"John\", \"Jane\", \"Michael\", \"Emily\", \"Chris\", \"Katie\", \"James\", \"Sarah\", \"David\", \"Laura\"];                     var lastNames = [\"Smith\", \"Johnson\", \"Williams\", \"Jones\", \"Brown\", \"Davis\", \"Miller\", \"Wilson\", \"Moore\", \"Taylor\"];                     var firstName = firstNames[Math.floor(Math.random() * firstNames.length)];                     var lastName = lastNames[Math.floor(Math.random() * lastNames.length)];                     return firstName + \" \" + lastName;                 })();"));
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).sendKeys(vars.get("randomname").toString());
        driver.findElement(By.id("email")).click();
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("inlazeuser2@yopmail.com");
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'password\']")).click();
        vars.put("generatedpassword", js.executeScript("return (function generatePassword() {                     var length = 8,                         charset = \"abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+<>?\",                         retVal = \"\";                     retVal += \"abcdefghijklmnopqrstuvwxyz\".charAt(Math.floor(Math.random() * 26));                     ;                     retVal += \"0123456789\".charAt(Math.floor(Math.random() * 10));                     retVal += \"!@#$%^&*()_+<>?\".charAt(Math.floor(Math.random() * 17));                     for (var i = retVal.length; i < length; ++i) {                         retVal += charset.charAt(Math.floor(Math.random() * charset.length));                     }                     return retVal.split(\'\').sort(function(){return 0.5-Math.random()}).join(\'\');                 })();"));
        vars.put("password", vars.get("generatedpassword").toString());
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys(vars.get("password").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).click();
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).sendKeys(vars.get("password").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.cssSelector(".flex-col:nth-child(2)")).click();
    }
    @Test
    public void registroinvalidocorreo() {
        driver.get("https://test-qa.inlaze.com/auth/sign-up");
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        vars.put("randomname", js.executeScript("return (function generateRandomName() {                     var firstNames = [\"John\", \"Jane\", \"Michael\", \"Emily\", \"Chris\", \"Katie\", \"James\", \"Sarah\", \"David\", \"Laura\"];                     var lastNames = [\"Smith\", \"Johnson\", \"Williams\", \"Jones\", \"Brown\", \"Davis\", \"Miller\", \"Wilson\", \"Moore\", \"Taylor\"];                     var firstName = firstNames[Math.floor(Math.random() * firstNames.length)];                     var lastName = lastNames[Math.floor(Math.random() * lastNames.length)];                     return firstName + \" \" + lastName;                 })();"));
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).sendKeys(vars.get("randomname").toString());
        driver.findElement(By.id("email")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        vars.put("email", js.executeScript("var invalidEmail = \'user\' + Math.floor(Math.random() * 1000) + \'@example\'; return invalidEmail;"));
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys(vars.get("email").toString());
        driver.findElement(By.xpath("//input[@id=\'password\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        vars.put("generatedpassword", js.executeScript("return (function generatePassword() {                     var length = 8,                         charset = \"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+<>?\",                         retVal = \"\";                     retVal += \"abcdefghijklmnopqrstuvwxyz\".charAt(Math.floor(Math.random() * 26));                     retVal += \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\".charAt(Math.floor(Math.random() * 26));                     retVal += \"0123456789\".charAt(Math.floor(Math.random() * 10));                     retVal += \"!@#$%^&*()_+<>?\".charAt(Math.floor(Math.random() * 17));                     for (var i = retVal.length; i < length; ++i) {                         retVal += charset.charAt(Math.floor(Math.random() * charset.length));                     }                     return retVal.split(\'\').sort(function(){return 0.5-Math.random()}).join(\'\');                 })();"));
        vars.put("password", vars.get("generatedpassword").toString());
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys(vars.get("password").toString());
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).click();
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).sendKeys(vars.get("password").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        assertThat(driver.findElement(By.cssSelector(".ml-3")).getText(), is("Successful registration!"));
    }
    @Test
    public void registroinvalidonombre() {
        driver.get("https://test-qa.inlaze.com/auth/sign-up");
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).click();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        vars.put("randomname", js.executeScript("return (function generateRandomName() {                     var firstNames = [\"John\", \"Jane\", \"Michael\", \"Emily\", \"Chris\", \"Katie\", \"James\", \"Sarah\", \"David\", \"Laura\"];                                          var firstName = firstNames[Math.floor(Math.random() * firstNames.length)];                                          return firstName                  })();"));
        driver.findElement(By.xpath("//input[@id=\'full-name\']")).sendKeys(vars.get("randomname").toString());
        driver.findElement(By.id("email")).click();
        driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("inlazeuser2@yopmail.com");
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'password\']")).click();
        vars.put("generatedpassword", js.executeScript("return (function generatePassword() {                     var length = 8,                         charset = \"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+<>?\",                         retVal = \"\";                     retVal += \"abcdefghijklmnopqrstuvwxyz\".charAt(Math.floor(Math.random() * 26));                     retVal += \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\".charAt(Math.floor(Math.random() * 26));                     retVal += \"0123456789\".charAt(Math.floor(Math.random() * 10));                     retVal += \"!@#$%^&*()_+<>?\".charAt(Math.floor(Math.random() * 17));                     for (var i = retVal.length; i < length; ++i) {                         retVal += charset.charAt(Math.floor(Math.random() * charset.length));                     }                     return retVal.split(\'\').sort(function(){return 0.5-Math.random()}).join(\'\');                 })();"));
        vars.put("password", vars.get("generatedpassword").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys(vars.get("password").toString());
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).click();
        driver.findElement(By.xpath("//input[@id=\'confirm-password\']")).sendKeys(vars.get("password").toString());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        driver.findElement(By.cssSelector(".flex-col:nth-child(2)")).click();
    }
}
